### PR TITLE
Add option in config for data collection server.

### PR DESCRIPTION
**Pull request by benjamin238**
adds an option in the config for the data collection server (so we can sell baronvros user data)

/s

### CODE REVIEW

**Comment by thehydrogen** [comment]
Just reminding you: End-User Data, according to Discord, must be handled securely and can't be stored plaintext. This means that just having a site with data about users is against Discord's guidelines.

**Comment by Artuto** [comment]
Hilarious someone cares about that

**Comment by benjamin238** [comment]
@thehydrogen did you not see the /s

**Comment by TheMegaEagle** [comment]
he's quite obviously doing this because his bot is being replaced

**Pull request merged**
